### PR TITLE
Next15 support

### PR DESCRIPTION
**Pull request by cmaycumber**
Adds support for breaking changing in NextJS 15 fixing #113 

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by thomasballinger** [comment]
Hm it's a bummer for this change to break everyone still using Next.js 14. Maybe we could change some APIs to allow promises, like in the docs change here allowing a `Promise<string>` for the token. Otherwise we're requiring a change on upgrade.

**Comment by thomasballinger** [comment]
Let's go ahead and require that Next.js 14 users have to make changes, but let's change the TypeScript types here to make sure we don't call `.then()` on something that is only a promise in Next.js 15.

**Comment by cmaycumber** [comment]
Got it. This was a bit quick and dirty. I'll try to clean up some of the awaits as well to make the code a little more readable.

**Comment by thomasballinger** [comment]
i can pick it up, feel free to leave as is if you haven't! But that sounds great

**Comment by thomasballinger** [comment]
OK there's more to do here, but this is great so far.
- create an example repo (or update test-nextjs in this one) to show this working.
- open up the peerDependencies like
```
  "peerDependencies": {
    "next": "^14.0.3 || ^15.0.0",
    "react": "^18 || ^19.0.0-0",
  },
  ```

But let's not block an alpha on all that. @cmaycumber is this working for you in a Next.js 15 app? Do you see peer dependency warnings you have to ignore?

**Comment by thomasballinger** [comment]
I'm going to set up a Next.js 15 example, get it running automated tests, point it at this PR, and if everything works with this this PR seems good to publish as an alpha.

**Comment by thomasballinger** [comment]
Here's a Next.js 15 demo using this branch (published as `@convex-dev/auth@0.0.75-alpha.1`) and a new convex alpha (`convex@1.17.1-alpha.1`): https://github.com/get-convex/convex-auth-test-next15

**Comment by thomasballinger** [comment]
Thanks @cmaycumber, merged in as https://github.com/get-convex/convex-auth/pull/125

**Pull request closed without merging**
